### ISSUE TITLE
Bug with stylesheet

### ISSUE THREAD

**Issue by Amnish04** [avelynhc/til_tracker#10]
When using the `-s` option, the stylesheet isn't linked correctly to the generated files.

For example, for the following file structure,
![image](https://github.com/avelynhc/til_tracker/assets/78865303/97fd26ff-03ad-403c-a3ae-801abcd02a1c)

The user would execute:
```
ts-node .\src\index.ts .\examples\ -s .\examples\styles\stylesheet.css
```

This generates
![image](https://github.com/avelynhc/til_tracker/assets/78865303/d9230a84-74d3-4768-9def-ece9f5e99d2b)

which is the correct path from user's perspective, but since the files are generated in a different directory from the user, an adjusted path is expected.

In this example, should be
```
.\examples\styles\stylesheet.css
```

**Comment by avelynhc** [comment]
@Amnish04 are you going to implement this new feature? if not, I can close the issue. Let me know. Thanks!

**Comment by Amnish04** [comment]
@avelynhc I will try to add this one as soon as I find some time. Will create a PR once ready
