### ISSUE TITLE
Clarification Needed for File vs. Folder Input

### ISSUE THREAD

**Issue by mnajibi** [avelynhc/til_tracker#2]
The documentation mentions that users can specify either a file or folder as input for conversion. It's not clear how the tool handles scenarios where a file and a folder share the same name. Clearer guidelines or error messages in such cases would help in improving user experience.

**Comment by avelynhc** [comment]
Information regarding this issue has been added to `README.md` as below. 
```text
Note: Even if a file and a folder share the same name, you will still be able to obtain the desired result. 
Since folders do not have file extensions, there is no confusion between the folder and the file.
```
