### ISSUE TITLE
Add support for config files via -c / --config flag

### ISSUE THREAD

**Issue by rook4715** [avelynhc/til_tracker#20]
I would like to add a new feature to til_tracker, the aibility to use a TOML file to specify options.
- The new `-c` / `--config` flag will accept a filepath to a TOML file.
- If the file is missing or otherwise cannot be parsed as TOML, an error message will be displayed.
- Options specified in the TOML file will override options on the command line.
- Options not specified in the TOML file will assume default options (e.g., if `lang` is not specified in the TOML file, it will default to `en-CA`).

**Comment by avelynhc** [comment]
@rook4715 For sure. Go for it!
