### ISSUE TITLE
Specific Type Annotations for readFile Function Parameters

### ISSUE THREAD

**Issue by mnajibi** [avelynhc/til_tracker#4]
The `readFile` function uses the type `any` for its parameters, which can lead to potential runtime issues and reduces the advantages of TypeScript's type-checking. The types should be more specific, e.g., `inputPath: string`.

**Comment by avelynhc** [comment]
Change has been made as below.
``` ts
module.exports.readFile = function (inputPath: string, cssLink: string, outputFolder: string){...}
```
