### ISSUE TITLE
Lack of Validation for CSS Stylesheet URLs

### ISSUE THREAD

**Issue by mnajibi** [avelynhc/til_tracker#5]
When specifying a stylesheet URL using the -s or --stylesheet option, there is no validation mechanism in place to check if the provided URL is valid or if it points to an actual CSS file. This can lead to broken styles in the generated HTML if an invalid URL is provided. Add a validation check for the provided CSS URL to ensure it's valid and accessible. Display a warning or error message if the URL is invalid or inaccessible.

**Comment by avelynhc** [comment]
When a user enters the wrong stylesheet URL, CSS won't be applied to the HTML, and the user will see an error. I don't believe it's the CLI's responsibility. When users encounter errors, they will take steps to correct them.
